### ISSUE TITLE
Possible support for mobile

### ISSUE THREAD

**Issue by AbandonedCart** [AMGarkin/BDOcrypt#3]
I was trying to decrypt the mobile loc files and keep running into a segfault 11 and was hoping you may be able to shed some light on it.

The loc file is https://mega.nz/#!ZtBmjQgJ!9W3n0CEx7GSuJ_Qop_fGP3o_6Q5SjdLG1WHD2L2kQC8 (can be uploaded elsewhere, if necessary)

Also, if you are interested, I put together a makefile that will build for linux / macos (I am a Mac user) that has been verified against the desktop BDO. I can submit a PR for that.

**Comment by AMGarkin** [comment]
This .loc file is almost the same as on PC. there are only 2 differences - texts are in UTF-8 instead UTF-16 and line break is CR+LF instead of just LF.

Source files for BDO mobile:
https://github.com/AMGarkin/BDOcrypt/blob/master/BDO_decrypt-mobile.c
https://github.com/AMGarkin/BDOcrypt/blob/master/BDO_encrypt-mobile.c

**Comment by AbandonedCart** [comment]
Impressive. I suspected the CLRF, but didn't even realize the UTF-8 until you said it. Regardless, I am sure you will have made a lot of people very happy now that a patch will be possible. Thanks.
